//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mozlite.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功添加了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Created {
            get {
                return ResourceManager.GetString("DataAction_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，添加“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_CreatedFailured {
            get {
                return ResourceManager.GetString("DataAction_CreatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功删除了所选择的{0}。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Deleted {
            get {
                return ResourceManager.GetString("DataAction_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailured {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，删除“{0}”失败了，因为包含的子项不为空。 的本地化字符串。
        /// </summary>
        internal static string DataAction_DeletedFailuredItemsNotEmpty {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailuredItemsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，“{0}”已经存在，操作失败。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Duplicate {
            get {
                return ResourceManager.GetString("DataAction_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功完成了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Success {
            get {
                return ResourceManager.GetString("DataAction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，发生了未知错误，操作失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UnknownError {
            get {
                return ResourceManager.GetString("DataAction_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜你，你已经成功更新了“{0}”。 的本地化字符串。
        /// </summary>
        internal static string DataAction_Updated {
            get {
                return ResourceManager.GetString("DataAction_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，更新“{0}”失败了。 的本地化字符串。
        /// </summary>
        internal static string DataAction_UpdatedFailured {
            get {
                return ResourceManager.GetString("DataAction_UpdatedFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通会员 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对数据库中某些列进行分词，生成搜索需求文档，提供前天搜索服务。 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Description {
            get {
                return ResourceManager.GetString("Task_Searching_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索引擎服务 的本地化字符串。
        /// </summary>
        internal static string Task_Searching_Name {
            get {
                return ResourceManager.GetString("Task_Searching_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [服务]{0}执行错误：{1}。 的本地化字符串。
        /// </summary>
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
    }
}
