//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Extensions.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mozlite.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DataAction_Created {
            get {
                return ResourceManager.GetString("DataAction_Created", resourceCulture);
            }
        }
        
        internal static string DataAction_CreatedFailured {
            get {
                return ResourceManager.GetString("DataAction_CreatedFailured", resourceCulture);
            }
        }
        
        internal static string DataAction_Deleted {
            get {
                return ResourceManager.GetString("DataAction_Deleted", resourceCulture);
            }
        }
        
        internal static string DataAction_DeletedFailured {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailured", resourceCulture);
            }
        }
        
        internal static string DataAction_DeletedFailuredItemsNotEmpty {
            get {
                return ResourceManager.GetString("DataAction_DeletedFailuredItemsNotEmpty", resourceCulture);
            }
        }
        
        internal static string DataAction_Duplicate {
            get {
                return ResourceManager.GetString("DataAction_Duplicate", resourceCulture);
            }
        }
        
        internal static string DataAction_Success {
            get {
                return ResourceManager.GetString("DataAction_Success", resourceCulture);
            }
        }
        
        internal static string DataAction_UnknownError {
            get {
                return ResourceManager.GetString("DataAction_UnknownError", resourceCulture);
            }
        }
        
        internal static string DataAction_Updated {
            get {
                return ResourceManager.GetString("DataAction_Updated", resourceCulture);
            }
        }
        
        internal static string DataAction_UpdatedFailured {
            get {
                return ResourceManager.GetString("DataAction_UpdatedFailured", resourceCulture);
            }
        }
        
        internal static string TaskExecuteError {
            get {
                return ResourceManager.GetString("TaskExecuteError", resourceCulture);
            }
        }
        
        internal static string Task_Searching_Description {
            get {
                return ResourceManager.GetString("Task_Searching_Description", resourceCulture);
            }
        }
        
        internal static string Task_Searching_Name {
            get {
                return ResourceManager.GetString("Task_Searching_Name", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ErrorDescriptor_ConcurrencyFailure", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_DefaultError {
            get {
                return ResourceManager.GetString("ErrorDescriptor_DefaultError", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_DuplicateEmail {
            get {
                return ResourceManager.GetString("ErrorDescriptor_DuplicateEmail", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_DuplicateRoleName {
            get {
                return ResourceManager.GetString("ErrorDescriptor_DuplicateRoleName", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_DuplicateUserName {
            get {
                return ResourceManager.GetString("ErrorDescriptor_DuplicateUserName", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorDescriptor_InvalidEmail", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_InvalidRoleName {
            get {
                return ResourceManager.GetString("ErrorDescriptor_InvalidRoleName", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_InvalidToken {
            get {
                return ResourceManager.GetString("ErrorDescriptor_InvalidToken", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_InvalidUserName {
            get {
                return ResourceManager.GetString("ErrorDescriptor_InvalidUserName", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("ErrorDescriptor_LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_NullSecurityStamp {
            get {
                return ResourceManager.GetString("ErrorDescriptor_NullSecurityStamp", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordMismatch", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordRequiresLower", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordRequiresUpper", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordTooShort {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordTooShort", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_RoleNotFound {
            get {
                return ResourceManager.GetString("ErrorDescriptor_RoleNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("ErrorDescriptor_RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserAlreadyInRole", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserLockedOut {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserLockedOut", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserNameNotFound {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserNameNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserNotInRole {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserNotInRole", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("ErrorDescriptor_PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_UserNotFound {
            get {
                return ResourceManager.GetString("ErrorDescriptor_UserNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorDescriptor_DuplicateNormalizedRoleName {
            get {
                return ResourceManager.GetString("ErrorDescriptor_DuplicateNormalizedRoleName", resourceCulture);
            }
        }
        
        internal static string PermissionValue_Allow {
            get {
                return ResourceManager.GetString("PermissionValue_Allow", resourceCulture);
            }
        }
        
        internal static string PermissionValue_Deny {
            get {
                return ResourceManager.GetString("PermissionValue_Deny", resourceCulture);
            }
        }
        
        internal static string PermissionValue_NotSet {
            get {
                return ResourceManager.GetString("PermissionValue_NotSet", resourceCulture);
            }
        }
        
        internal static string PermissionSetCannotBeOwner {
            get {
                return ResourceManager.GetString("PermissionSetCannotBeOwner", resourceCulture);
            }
        }
        
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        internal static string EmailTaskService {
            get {
                return ResourceManager.GetString("EmailTaskService", resourceCulture);
            }
        }
        
        internal static string EmailTaskService_Description {
            get {
                return ResourceManager.GetString("EmailTaskService_Description", resourceCulture);
            }
        }
    }
}
