//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Extensions.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mozlite.Extensions.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 激活&quot;[$site;]&quot;的账户 的本地化字符串。
        /// </summary>
        public static string Email_ActiveAccount {
            get {
                return ResourceManager.GetString("Email_ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [$name;] 先生/小姐：&lt;br/&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;你好&lt;br/&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;你还没有激活[$site;]网站注册的账户，点击链接（本链接24小时内有效）进行激活&lt;a href=&quot;[$link;]&quot; target=&quot;_blank&quot;&gt;[$link;]&lt;/a&gt;...&lt;br/&gt;&lt;br/&gt;
        ///&lt;div style=&quot;text-align:right; margin-right:10px&quot;&gt;[$site;]团队 敬上&lt;/div&gt;
        ///&lt;div style=&quot;text-align:right; margin-right:10px&quot;&gt;[$today;]&lt;/div&gt; 的本地化字符串。
        /// </summary>
        public static string Email_ActiveAccount_Body {
            get {
                return ResourceManager.GetString("Email_ActiveAccount_Body", resourceCulture);
            }
        }
    }
}
