//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Mvc.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mozlite.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AllowViewMenuPermission {
            get {
                return ResourceManager.GetString("AllowViewMenuPermission", resourceCulture);
            }
        }
        
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        internal static string DaysBefore {
            get {
                return ResourceManager.GetString("DaysBefore", resourceCulture);
            }
        }
        
        internal static string ErrorCode_AuthorizeFailure {
            get {
                return ResourceManager.GetString("ErrorCode_AuthorizeFailure", resourceCulture);
            }
        }
        
        internal static string ErrorCode_Failured {
            get {
                return ResourceManager.GetString("ErrorCode_Failured", resourceCulture);
            }
        }
        
        internal static string ErrorCode_InvalidParameter {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidParameter", resourceCulture);
            }
        }
        
        internal static string ErrorCode_InvalidToken {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidToken", resourceCulture);
            }
        }
        
        internal static string ErrorCode_NullParameter {
            get {
                return ResourceManager.GetString("ErrorCode_NullParameter", resourceCulture);
            }
        }
        
        internal static string ErrorCode_Succeeded {
            get {
                return ResourceManager.GetString("ErrorCode_Succeeded", resourceCulture);
            }
        }
        
        internal static string ErrorCode_TokenExpired {
            get {
                return ResourceManager.GetString("ErrorCode_TokenExpired", resourceCulture);
            }
        }
        
        internal static string ErrorCode_UnknownError {
            get {
                return ResourceManager.GetString("ErrorCode_UnknownError", resourceCulture);
            }
        }
        
        internal static string HoursBefore {
            get {
                return ResourceManager.GetString("HoursBefore", resourceCulture);
            }
        }
        
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        internal static string LogAction_Add {
            get {
                return ResourceManager.GetString("LogAction_Add", resourceCulture);
            }
        }
        
        internal static string LogAction_AddFormat {
            get {
                return ResourceManager.GetString("LogAction_AddFormat", resourceCulture);
            }
        }
        
        internal static string LogAction_Modify {
            get {
                return ResourceManager.GetString("LogAction_Modify", resourceCulture);
            }
        }
        
        internal static string LogAction_ModifyFormat {
            get {
                return ResourceManager.GetString("LogAction_ModifyFormat", resourceCulture);
            }
        }
        
        internal static string LogAction_Remove {
            get {
                return ResourceManager.GetString("LogAction_Remove", resourceCulture);
            }
        }
        
        internal static string LogAction_RemoveFormat {
            get {
                return ResourceManager.GetString("LogAction_RemoveFormat", resourceCulture);
            }
        }
        
        internal static string MunitesBefore {
            get {
                return ResourceManager.GetString("MunitesBefore", resourceCulture);
            }
        }
        
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        internal static string NumberPage {
            get {
                return ResourceManager.GetString("NumberPage", resourceCulture);
            }
        }
        
        internal static string SelectDefaultText {
            get {
                return ResourceManager.GetString("SelectDefaultText", resourceCulture);
            }
        }
        
        internal static string YearDateFormat {
            get {
                return ResourceManager.GetString("YearDateFormat", resourceCulture);
            }
        }
        
        internal static string Mozmd_ModePreview {
            get {
                return ResourceManager.GetString("Mozmd_ModePreview", resourceCulture);
            }
        }
        
        internal static string Mozmd_FullScreen {
            get {
                return ResourceManager.GetString("Mozmd_FullScreen", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Header {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Header", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Bold {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Bold", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Italic {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Italic", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Code {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Code", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Ul {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ul", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Ol {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ol", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Link {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Link", resourceCulture);
            }
        }
        
        internal static string Mozmd_Syntax_Quote {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Quote", resourceCulture);
            }
        }
    }
}
