//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozlite.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mozlite.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 允许查看“{0}”菜单功能！ 的本地化字符串。
        /// </summary>
        internal static string AllowViewMenuPermission {
            get {
                return ResourceManager.GetString("AllowViewMenuPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MM月dd日 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天前 的本地化字符串。
        /// </summary>
        internal static string DaysBefore {
            get {
                return ResourceManager.GetString("DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_AuthorizeFailure {
            get {
                return ResourceManager.GetString("ErrorCode_AuthorizeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_Failured {
            get {
                return ResourceManager.GetString("ErrorCode_Failured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”无效! 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_InvalidParameter {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POST的数据无效！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_InvalidPostData {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidPostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌无效！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_InvalidToken {
            get {
                return ResourceManager.GetString("ErrorCode_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到{0}！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_NotFound {
            get {
                return ResourceManager.GetString("ErrorCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”不能为空! 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_NullParameter {
            get {
                return ResourceManager.GetString("ErrorCode_NullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_Succeeded {
            get {
                return ResourceManager.GetString("ErrorCode_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌过期！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_TokenExpired {
            get {
                return ResourceManager.GetString("ErrorCode_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，发生了未知的错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCode_UnknownError {
            get {
                return ResourceManager.GetString("ErrorCode_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        internal static string HoursBefore {
            get {
                return ResourceManager.GetString("HoursBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刚刚 的本地化字符串。
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增了 的本地化字符串。
        /// </summary>
        internal static string LogAction_Add {
            get {
                return ResourceManager.GetString("LogAction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string LogAction_AddFormat {
            get {
                return ResourceManager.GetString("LogAction_AddFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改了 的本地化字符串。
        /// </summary>
        internal static string LogAction_Modify {
            get {
                return ResourceManager.GetString("LogAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”由”{1}“修改为“{2}” 的本地化字符串。
        /// </summary>
        internal static string LogAction_ModifyFormat {
            get {
                return ResourceManager.GetString("LogAction_ModifyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除了 的本地化字符串。
        /// </summary>
        internal static string LogAction_Remove {
            get {
                return ResourceManager.GetString("LogAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“(”{1}“) 的本地化字符串。
        /// </summary>
        internal static string LogAction_RemoveFormat {
            get {
                return ResourceManager.GetString("LogAction_RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏显示 的本地化字符串。
        /// </summary>
        internal static string Mozmd_FullScreen {
            get {
                return ResourceManager.GetString("Mozmd_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        internal static string Mozmd_ModePreview {
            get {
                return ResourceManager.GetString("Mozmd_ModePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Bold {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Code {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Header {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Image {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Italic {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Link {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Ol {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Quote {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string Mozmd_Syntax_Ul {
            get {
                return ResourceManager.GetString("Mozmd_Syntax_Ul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        internal static string MunitesBefore {
            get {
                return ResourceManager.GetString("MunitesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 的本地化字符串。
        /// </summary>
        internal static string NumberPage {
            get {
                return ResourceManager.GetString("NumberPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string SelectDefaultText {
            get {
                return ResourceManager.GetString("SelectDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy年MM月dd日 的本地化字符串。
        /// </summary>
        internal static string YearDateFormat {
            get {
                return ResourceManager.GetString("YearDateFormat", resourceCulture);
            }
        }
    }
}
